name: build-and-deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    steps:
    - name: ssh connection and commands
      uses: JimCronqvist/action-ssh@master
      env:
        NAME: "admin"
      with:
        hosts: 'admin@209.126.6.227'
        privateKey: ${{ secrets.PRIVATE_KEY }}
        debug: false
        command: |
          cd ~/lwview2
          git stash
          git pull
          podman build -t lwview/lwviewsite:latest .
          cd ~
          podman save lwviewsite:latest > lwviewsite.tar
          