name: build-and-deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh connection
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/prod.key
        chmod 600 ~/.ssh/prod.key
        cat >>~/.ssh/config <<END
          Host prod
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/prod.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: admin
        SSH_KEY: ${{ secrets.PRIVATE_KEY }}
        SSH_HOST: 209.126.6.227
    - name: build
      run: ssh prod 'echo test'