name: build-and-deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh connection and commands
      uses: JimCronqvist/action-ssh@master
      env:
        NAME: "admin"
      with:
        hosts: 'admin@209.126.6.227'
        privateKey: ${{ secrets.PRIVATE_KEY }}
        debug: false
        command: |
          cd ~/lwview2
          git stash
          git pull
          podman rmi lwviewsite:latest -f
          podman build -t lwview/lwviewsite:latest .
          cd ~
          rm lwviewsite.tar
          podman save lwviewsite:latest > lwviewsite.tar
          /snap/bin/microk8s.ctr image import lwviewsite.tar
          cd ~/deployment
          /snap/bin/microk8s.kubectl apply -f lwview.yaml
          exit 0